baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cb7d"
theme = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
paginate = 5
disqusShortname = "YOUR_SHORT_NAME_HERE"
copyright = "All rights reserved - 2020"
canonifyurls = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Cb7d 's blog."

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Cb7d"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/portfolio"
    text = "portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "who is Cb7d?"

[imaging]
    quality = 75